name: Ejercicio 5
on:
  push:
env:
  APP_NAME: "Quiz App"
  VERSION: "1.0.0"
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.create-timestamp.outputs.timestamp }}
    steps:
      - name: Imprimir info global
        run: echo "Iniciando $APP_NAME v$VERSION"
      - id: create-timestamp
        name: Crear timestamp output
        run: echo "timestamp=$(date +%s)" >> $GITHUB_OUTPUT
  test:
    needs: setup
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - run: npm install
      - run: npm test
      - name: Ver timestamp del setup
        run: echo "Timestamp recibido: ${{ needs.setup.outputs.timestamp }}"
  deploy:
    needs: test
    if: github.ref == "refs/heads/main"
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
    steps:
      - name: Simular despliegue
        run: echo "Desplegando $APP_NAME v$VERSION"
      - name: Verificar Secret
        run: |
          if [ -n "$API_KEY" ]; then
            echo "Secret configurada correctamente"
          else
            echo "Error: Secret no encontrada"
            exit 1
          fi
