name: "Ejercicio 1"

on:
  push:
    branches: [ main ]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Saludo
        run: echo "Hola, mi nombre es Fabio Cesar Lagos Nataren"

      - name: Fecha y hora
        run: date

      - name: Sistema operativo
        run: echo "Sistema operativo: $RUNNER_OS"
